version: '1.0'
stages:
  - checkout
  - package
  - deploy  
steps:
  clone:
    title: Cloning main repository...
    type: git-clone
    arguments:
      repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
      revision: '${{CF_REVISION}}'
    stage: checkout
  BuildingDockerImage:
    title: Building Docker Image
    type: build
    working_directory: ${{clone}}
    arguments:
      image_name: frankzhu2003/codefresh
      tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
      dockerfile: Dockerfile
    stage: package
#  deploy:
#    title: Storing Helm chart
#    type: helm
#    stage: deploy
#    working_directory: ./python-flask-sample-app
#    arguments:
#      action: push
#      chart_name: charts/python
#      helm_version: 3.0.2
#      kube_context: frankz-jfrog-platform@soleng-dev
  DeployMyChart:
    type: helm
    stage: deploy
    working_directory: ./python-flask-sample-app
    arguments:
      action: install
      chart_name: charts/python
      release_name: my-python-chart
      helm_version: 3.0.2
      kube_context: frankz-jfrog-platform@soleng-dev
      custom_values:
      - 'buildID=${{CF_BUILD_ID}}'
      - 'image_pullPolicy=Always'
      - 'image_repository=frankzhu2003/codefresh'
      - 'image_tag=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
     # - 'image_pullSecret=codefresh-generated-r.cfcr.io-cfcr-default'      
